### ISSUE TITLE
Add legend hide options to timeseries panel

### ISSUE THREAD

**Issue by GretaCB** [rhowe/grafonnet-lib#18]
Hi there,

Firstly, really appreciate all the work you've done on this fork 🙌 

I'm interested in adding the `hideZero` property to the legend object for Time Series Panels, similar to the [Graph Panel](https://github.com/rhowe/grafonnet-lib/blob/1739068a984b63a51aadf74a0bb8f1a473b60727/grafonnet/graph_panel.libsonnet#L120), and I am currently using Grafana v9.2

I attempted to create a new branch in order to submit a PR, but I don't have permissions. So I am opening a ticket with a suggested diff:

```diff
     legendMode='list',
     legendPlacement='bottom',
     legendValues=[],
+    legendHideEmpty=null,
+    legendHideZero=null,
     lineInterpolation='linear',
     lineStyle='solid',
     lineDashSegments=null,
@@ -181,6 +183,8 @@
         calcs: legendValues,
         displayMode: legendMode,
         placement: legendPlacement,
+        [if legendHideEmpty != null then 'hideEmpty']: legendHideEmpty,
+        [if legendHideZero != null then 'hideZero']: legendHideZero,
       },
       tooltip: {
```

Thank you!

**Comment by rhowe** [comment]
Hey, glad you think so. It looks like this feature isn't present in the timeseries panel - see this post and linked discussion threads: https://community.grafana.com/t/how-to-hide-zero-or-null-values-in-legend-in-grafana-8/54369/8

_however_ it looks like you'll be able to do this with a transformer in 9.4.0: https://github.com/grafana/grafana/pull/57657

As for creating a branch, you should be able to fork the repository into your own github account and create as many branches as you like there. If you make changes in your fork and would like them to be incorporated in this fork you can raise a pull request.

How does all that sound?

**Comment by GretaCB** [comment]
Ahhh I see, I appreciate the forum link! I'll give that alternative approach a whirl. And will keep an eye out for the new transformation implementation for this once I update to 9.4. Thank you! 

Closing this issue.
