### ISSUE TITLE
[Suggestion] Generate jsonnet from json

### ISSUE THREAD

**Issue by jacksongoode** [rhowe/grafonnet-lib#21]
It might be interesting to add this to the fork, https://github.com/grafana/grafonnet-lib/pull/380!

If so I can help port it over!

**Comment by malcolmholmes** [comment]
I'd like to think that it'll make the fork redundant. As the schema grows, it'll cover everything that Grafana itself knows about.

Note, that currently the code in that PR depends on a code generator that is not yet public. Coming, but not quite yet. We'll get there.

**Comment by jacksongoode** [comment]
Ahh I see I was thinking that this was the tool itself. Well, very excited to see it!

**Comment by rhowe** [comment]
Yep I would very much like to delete this fork too, but for now I'm happy to keep it limping along manually.
I'm interested in the schema-generation stuff and perhaps some of the changes in this fork can help inspire/validate the generated code?

**Comment by malcolmholmes** [comment]
The generated library will have two components: code that is autogenerated directly from the schema, plus a "veneer" that adds convenience methods on top of the generated code. Once we've got the generation working, there will be work making sure the veneer is functional and useful.

Note, this new library will not be back-compatible with the old Grafonnet (e.g. it won't use the builder pattern, which performs badly in Jsonnet).

**Comment by jacksongoode** [comment]
@malcolmholmes This is great news! Regarding the compatibility with Grafonnet, the new schema generated will be valid Jsonnet right? Or will it use its own builder/templater?

**Comment by malcolmholmes** [comment]
The schema that is being built into Grafana uses CUE to express the schema. That can be rendered into a number of formats (Golang, TypeScript/etc), one of which is JSON Schema. With @duologic's https://github.com/Duologic/crdsonnet/, we can render a Jsonnet lib directly from that JSON schema. Then, there's a reasonable amount of plumbing, and the vaneer I mentioned above to get right.

**Comment by rhowe** [comment]
I'm going to close this issue as if the CUE-derived library changes are completed and merged into the upstream grafonnet-lib, this fork hopefully ceases to be useful.

**Comment by malcolmholmes** [comment]
FWIW, we have a new version of grafonnet at https://github.com/grafana/grafonnet. This one is schematised, so to fix things, we fix them in Grafana itself. Because this is early, we're not going widely public yet, but we do welcome feedback.
